server:
  port: 8443
  ssl:
    enabled: true
    certificate: "classpath:${CERT_PEM}"
    certificate-private-key: "classpath:${KEY_PEM}"
#    key-store: classpath:keystore.p12
#    key-store-type: PKCS12
#    key-store-password: "${KEYSTORE_PASSWORD}"
    key-alias: example-websocket

version: "@project.version@"

domain-name: "${DOMAIN_NAME:localhost}"

spring:
  application:
    name: "example-websocket"
  datasource:
    url: "jdbc:mysql://${DB_URL:localhost}:${DB_PORT:3306}/example-websocket?createDatabaseIfNotExist=true"
    username: "${DB_USERNAME}"
    password: "${DB_PASSWORD}"
    driver-class-name: "com.mysql.cj.jdbc.Driver"
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: update
#  elasticsearch:
#    uris: https://localhost:9200
#    username: "@es_username@"
#    password: "@es_password@"
#    ssl:
#      enabled: true
#      certificate-authorities: classpath:http_ca.crt
  flyway:
    enabled: true
    url: "jdbc:mysql://${DB_URL:localhost}:${DB_PORT:3306}/example-websocket?createDatabaseIfNotExist=true"
    user: "${DB_USERNAME}"
    password: "${DB_PASSWORD}"
    driver-class-name: "com.mysql.cj.jdbc.Driver"
    locations:
      - classpath:db/migration
    baseline-on-migrate: true
  batch:
    jdbc:
      initialize-schema: ALWAYS
  mail:
    host: smtp.gmail.com
    port: 587
    username: "${HOST_EMAIL_ADDRESS}"
    password: "${HOST_EMAIL_PASSWORD}"
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    mode: HTML5
    cache: false

logging:
  level:
    org:
      springframework:
        web:
          socket: DEBUG
        messaging: DEBUG
